import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <head>
        <title>Calender Management</title>
      </head>
      <body>
        <nav style={{ display: 'flex', gap: '20px', padding: '10px', borderBottom: '1px solid #ddd' }}>
          <Link href="/calender">Calendar</Link>
          <Link href="/slots">Time Slots</Link>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}